baseURL = "https://kmxtaylor.github.io/"
defaultContentLanguage = "en"
theme = "terminal"

paginate = 5

[params]
  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "blue"

  # if you set this to 0, only submenu trigger will be visible
  # showMenuItems = 3 

  # show selector to switch language
  showLanguageSelector = true

  # set theme to full screen width
  fullWidthTheme = false

  # center theme with default width
  centerTheme = true

  # if your resource directory contains an image called `cover.(jpg|png|webp)`,
  # then the file will be used as a cover automatically.
  # With this option you don't have to put the `cover` param in a front-matter.
  autoCover = true

  # set post to show the last updated
  # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
  showLastUpdated = false

  # set a custom favicon (default is a `themeColor` square)
  favicon = "/img/wug.png"

  # Provide a string as a prefix for the last update date. By default, it looks like this: 2022-xx-xx [Updated: 2022-xx-xx] :: Author
  # updatedDatePrefix = "Updated"

  # set all headings to their default size (depending on browser settings)
  # it's set to `true` by default
  # oneHeadingSize = false

# [params.twitter]
#   # set Twitter handles for Twitter cards
#   # see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
#   # do not include @
#   creator = ""
#   site = ""

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    title = "Katie Taylor"
    subtitle = "Personal website of a software developer, language-lover, dancer and researcher of life"
    owner = "Katie Taylor"
    keywords = ""
    copyright = ""
    menuMore = "More menu options"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"
    footerText = "Theme modified from Terminal by"

    [languages.en.params.logo]
      logoText = "Katie Taylor"
      logoHomeLink = "/"

    [languages.en.menu]
      # [[languages.en.menu.main]]
      #   weight = 1
      #   identifier = "home"
      #   name = "Home"
      #   url = "/" # duplicates logoHomeLink
      # [[languages.en.menu.main]]
      #   weight = 2
      #   identifier = "portfolio"
      #   name = "Porfolio"
      #   url = "/portfolio"
      [[languages.en.menu.main]]
        weight = 3
        identifier = "linkedin"
        name = "LinkedIn"
        url = "https://www.linkedin.com/in/kmxtaylor/"
      [[languages.en.menu.main]]
        weight = 4
        identifier = "resume"
        name = "Resume"
        url = "https://drive.google.com/drive/folders/1vY9XcPnUM6TbOGlCW4wgI5_0iSSk2c9I?usp=sharing"
      [[languages.en.menu.main]]
        weight = 5
        identifier = "github"
        name = "GitHub"
        url = "https://github.com/kmxtaylor"
      [[languages.en.menu.main]]
        weight = 6
        identifier = "contact-me"
        name = "Contact Me"
        url = "https://forms.gle/2xvN97e12byjD1di8"
        # url = "/contact-me"

  [languages.es]
    languageName = "Español"
    weight = 2
    title = "Katie Taylor"
    subtitle = "Sitio web personal de una estudiante, programadora, políglota, y bailarina"
    owner = "Katie Taylor"
    keywords = ""
    copyright = ""
    menuMore = "Ver más"
    readMore = "Ver menos"
    readOtherPosts = "Leer más publicaciones"
    newerPosts = "Publicaciones más recientes"
    olderPosts = "Publicaciones más viejos"
    missingContentMessage = "No podría encontrarlo..."
    missingBackButtonLabel = "Regresar a la página de inicio"
    footerText = "Tema basado en Terminal por"

    [languages.es.params.logo]
      logoText = "Katie Taylor"
      logoHomeLink = "/"

    [languages.es.menu]
      # [[languages.es.menu.main]]
      #   weight = 1
      #   identifier = "home"
      #   name = "Inicio"
      #   url = "/" # duplicates logoHomeLink
      [[languages.es.menu.main]]
        weight = 2
        identifier = "linkedin"
        name = "LinkedIn"
        url = "https://www.linkedin.com/in/kmxtaylor/?locale=es_ES"
      [[languages.es.menu.main]]
        weight = 3
        identifier = "resume"
        name = "Resumen"
        url = "https://drive.google.com/drive/folders/1vY9XcPnUM6TbOGlCW4wgI5_0iSSk2c9I?usp=sharing"
      [[languages.es.menu.main]]
        weight = 4
        identifier = "github"
        name = "GitHub"
        url = "https://github.com/kmxtaylor"
      [[languages.es.menu.main]]
        weight = 5
        identifier = "contact-me"
        name = "Contacto"
        url = "https://forms.gle/2xvN97e12byjD1di8"
        # url = "/contact-me"